-- Battlechip names for MMBN 5 scripting, enjoy.

-- https://docs.google.com/spreadsheets/d/18qUmXQP_w6g7Guy_fpzaCCWph17cxSetR29n5WOxXKI/pubhtml

local chips = {};

chips.codes = {};
chips.codes[-1] = '-';
chips.codes[ 0] = 'A';
chips.codes[ 1] = 'B';
chips.codes[ 2] = 'C';
chips.codes[ 3] = 'D';
chips.codes[ 4] = 'E';
chips.codes[ 5] = 'F';
chips.codes[ 6] = 'G';
chips.codes[ 7] = 'H';
chips.codes[ 8] = 'I';
chips.codes[ 9] = 'J';
chips.codes[10] = 'K';
chips.codes[11] = 'L';
chips.codes[12] = 'M';
chips.codes[13] = 'N';
chips.codes[14] = 'O';
chips.codes[15] = 'P';
chips.codes[16] = 'Q';
chips.codes[17] = 'R';
chips.codes[18] = 'S';
chips.codes[19] = 'T';
chips.codes[20] = 'U';
chips.codes[21] = 'V';
chips.codes[22] = 'W';
chips.codes[23] = 'X';
chips.codes[24] = 'Y';
chips.codes[25] = 'Z';
chips.codes[26] = '*';
chips.codes['-'] = -1;
chips.codes['A'] =  0;
chips.codes['B'] =  1;
chips.codes['C'] =  2;
chips.codes['D'] =  3;
chips.codes['E'] =  4;
chips.codes['F'] =  5;
chips.codes['G'] =  6;
chips.codes['H'] =  7;
chips.codes['I'] =  8;
chips.codes['J'] =  9;
chips.codes['K'] = 10;
chips.codes['L'] = 11;
chips.codes['M'] = 12;
chips.codes['N'] = 13;
chips.codes['O'] = 14;
chips.codes['P'] = 15;
chips.codes['Q'] = 16;
chips.codes['R'] = 17;
chips.codes['S'] = 18;
chips.codes['T'] = 19;
chips.codes['U'] = 20;
chips.codes['V'] = 21;
chips.codes['W'] = 22;
chips.codes['X'] = 23;
chips.codes['Y'] = 24;
chips.codes['Z'] = 25;
chips.codes['*'] = 26;

chips.names = {};
chips.names[ -1] = "-";
chips.names[  0] = "Empty";
chips.names[  1] = "Cannon";
chips.names[  2] = "HiCannon";
chips.names[  3] = "M-Cannon";
chips.names[  4] = "AirShot";
chips.names[  5] = "AirHoc";
chips.names[  6] = "Boomer";
chips.names[  7] = "Silence";
chips.names[  8] = "Tornado";
chips.names[  9] = "WideSht1";
chips.names[ 10] = "WideSht2";
chips.names[ 11] = "WideSht3";
chips.names[ 12] = "MrkCan1";
chips.names[ 13] = "MrkCan2";
chips.names[ 14] = "MrkCan3";
chips.names[ 15] = "Vulcan1";
chips.names[ 16] = "Vulcan2";
chips.names[ 17] = "Vulcan3";
chips.names[ 18] = "Spreader";
chips.names[ 19] = "Thunder";
chips.names[ 20] = "IceSeed";
chips.names[ 21] = "Pulsar1";
chips.names[ 22] = "Pulsar2";
chips.names[ 23] = "Pulsar3";
chips.names[ 24] = "SpShake1";
chips.names[ 25] = "SpShake2";
chips.names[ 26] = "SpShake3";
chips.names[ 27] = "Static";
chips.names[ 28] = "LifeSync";
chips.names[ 29] = "MiniBomb";
chips.names[ 30] = "EnergBom";
chips.names[ 31] = "MegEnBom";
chips.names[ 32] = "GunDelS1";
chips.names[ 33] = "GunDelS2";
chips.names[ 34] = "GunDelS3";
chips.names[ 35] = "Quake1";
chips.names[ 36] = "Quake2";
chips.names[ 37] = "Quake3";
chips.names[ 38] = "CrakBom";
chips.names[ 39] = "ParaBom";
chips.names[ 40] = "ResetBom";
chips.names[ 41] = "BugBomb";
chips.names[ 42] = "GrasSeed";
chips.names[ 43] = "LavaSeed";
chips.names[ 44] = "CannBall";
chips.names[ 45] = "Geyser";
chips.names[ 46] = "BlkBomb";
chips.names[ 47] = "SeaSeed";
chips.names[ 48] = "Sword";
chips.names[ 49] = "WideSwrd";
chips.names[ 50] = "LongSwrd";
chips.names[ 51] = "WideBlde";
chips.names[ 52] = "LongBlde";
chips.names[ 53] = "WindRack";
chips.names[ 54] = "CustSwrd";
chips.names[ 55] = "VarSwrd";
chips.names[ 56] = "Slasher";
chips.names[ 57] = "MoonBld1";
chips.names[ 58] = "MoonBld2";
chips.names[ 59] = "MoonBld3";
chips.names[ 60] = "Katana1";
chips.names[ 61] = "Katana2";
chips.names[ 62] = "Katana3";
chips.names[ 63] = "TankCan1";
chips.names[ 64] = "TankCan2";
chips.names[ 65] = "TankCan3";
chips.names[ 66] = "RedFrut1";
chips.names[ 67] = "RedFrut2";
chips.names[ 68] = "RedFrut3";
chips.names[ 69] = "Skully1";
chips.names[ 70] = "Skully2";
chips.names[ 71] = "Skully3";
chips.names[ 72] = "DrilArm1";
chips.names[ 73] = "DrilArm2";
chips.names[ 74] = "DrilArm3";
chips.names[ 75] = "TimeBom1";
chips.names[ 76] = "TimeBom2";
chips.names[ 77] = "TimeBom3";
chips.names[ 78] = "Voltz1";
chips.names[ 79] = "Voltz2";
chips.names[ 80] = "Voltz3";
chips.names[ 81] = "Lance";
chips.names[ 82] = "YoYo";
chips.names[ 83] = "Wind";
chips.names[ 84] = "Fan";
chips.names[ 85] = "BoyBomb1";
chips.names[ 86] = "BoyBomb2";
chips.names[ 87] = "BoyBomb3";
chips.names[ 88] = "Guard1";
chips.names[ 89] = "Guard2";
chips.names[ 90] = "Guard3";
chips.names[ 91] = "CrakOut";
chips.names[ 92] = "DublCrak";
chips.names[ 93] = "TripCrak";
chips.names[ 94] = "Magnum";
chips.names[ 95] = "MetaGel";
chips.names[ 96] = "Snake";
chips.names[ 97] = "CircGun";
chips.names[ 98] = "Mine";
chips.names[ 99] = "RockCube";
chips.names[100] = "Fanfare";
chips.names[101] = "Discord";
chips.names[102] = "Timpani";
chips.names[103] = "VDoll";
chips.names[104] = "Astroid1";
chips.names[105] = "Astroid2";
chips.names[106] = "Astroid3";
chips.names[107] = "Recov10";
chips.names[108] = "Recov30";
chips.names[109] = "Recov50";
chips.names[110] = "Recov80";
chips.names[111] = "Recov120";
chips.names[112] = "Recov150";
chips.names[113] = "Recov200";
chips.names[114] = "Recov300";
chips.names[115] = "BusterUp";
chips.names[116] = "PanlGrab";
chips.names[117] = "AreaGrab";
chips.names[118] = "GrabRvng";
chips.names[119] = "GrabBnsh";
chips.names[120] = "SloGauge";
chips.names[121] = "FstGauge";
chips.names[122] = "PnlRetrn";
chips.names[123] = "Geddon1";
chips.names[124] = "Geddon2";
chips.names[125] = "Geddon3";
chips.names[126] = "RainyDay";
chips.names[127] = "ColorPt";
chips.names[128] = "ElemRage";
chips.names[129] = "Blinder";
chips.names[130] = "AirSpin1";
chips.names[131] = "AirSpin2";
chips.names[132] = "AirSpin3";
chips.names[133] = "Invisibl";
chips.names[134] = "BblWrap";
chips.names[135] = "Barrier";
chips.names[136] = "Barr100";
chips.names[137] = "Barr200";
chips.names[138] = "NrthWind";
chips.names[139] = "HolyPanl";
chips.names[140] = "AntiFire";
chips.names[141] = "AntiWatr";
chips.names[142] = "AntiElec";
chips.names[143] = "AntiWood";
chips.names[144] = "AntiNavi";
chips.names[145] = "AntiDmg";
chips.names[146] = "AntiSwrd";
chips.names[147] = "AntiRecv";
chips.names[148] = "CopyDmg";
chips.names[149] = "Attck+10";
chips.names[150] = "Navi+20";
chips.names[151] = "FireHit1";
chips.names[152] = "FireHit2";
chips.names[153] = "FireHit3";
chips.names[154] = "HotBody1";
chips.names[155] = "HotBody2";
chips.names[156] = "HotBody3";
chips.names[157] = "AqWhirl1";
chips.names[158] = "AqWhirl2";
chips.names[159] = "AqWhirl3";
chips.names[160] = "SideBub1";
chips.names[161] = "SideBub2";
chips.names[162] = "SideBub3";
chips.names[163] = "ElcReel1";
chips.names[164] = "ElcReel2";
chips.names[165] = "ElcReel3";
chips.names[166] = "CusVolt1";
chips.names[167] = "CusVolt2";
chips.names[168] = "CusVolt3";
chips.names[169] = "CrsShld1";
chips.names[170] = "CrsShld2";
chips.names[171] = "CrsShld3";
chips.names[172] = "WavePit";
chips.names[173] = "RedWave";
chips.names[174] = "MudWave";
chips.names[175] = "CactBal1";
chips.names[176] = "CactBal2";
chips.names[177] = "CactBal3";
chips.names[178] = "WoodNos1";
chips.names[179] = "WoodNos2";
chips.names[180] = "WoodNos3";

chips.names[187] = "DarkCirc";
chips.names[188] = "DrkSword";
chips.names[189] = "DarkInvs";
chips.names[190] = "DarkPlus";
chips.names[191] = "DrkLance";
chips.names[192] = "DarkWide";
chips.names[193] = "DarkThnd";
chips.names[194] = "DrkRecov";
chips.names[195] = "DarkMetr";
chips.names[196] = "DarkDril";
chips.names[197] = "DarkTorn";
chips.names[198] = "DrkSonic";

chips.names[201] = "LifeAur";
chips.names[202] = "Muramasa";
chips.names[203] = "Guardian";
chips.names[204] = "Anubis";
chips.names[205] = "Attck+30";
chips.names[206] = "BugFix";
chips.names[207] = "DblPoint";
chips.names[208] = "Snctuary";
chips.names[209] = "FullCust";
chips.names[210] = "Meteors";
chips.names[211] = "NumbrBl";
chips.names[212] = "Jealousy";
chips.names[213] = "Poltrgst";
chips.names[214] = "BlakWing";
chips.names[215] = "Otenko";
chips.names[216] = "JustcOne";
chips.names[217] = "NeoVari";
chips.names[218] = "Z Saver";
chips.names[219] = "GunDelEX";
chips.names[220] = "SuprVulc";

chips.names[221] = "Roll";
chips.names[222] = "RollSP";
chips.names[223] = "RollDS";
chips.names[224] = "GyroMan";
chips.names[224] = "GyroMan";
chips.names[225] = "GyromanSP";
chips.names[225] = "GyromanSP";
chips.names[226] = "GyromanDS";
chips.names[226] = "GyromanDS";
chips.names[227] = "NapalmMan";
chips.names[227] = "NapalmMan";
chips.names[228] = "NapalmManSP";
chips.names[228] = "NapalmManSP";
chips.names[229] = "NapalmManDS";
chips.names[229] = "NapalmManDS";
chips.names[230] = "SearchMan";
chips.names[230] = "SearchMan";
chips.names[231] = "SearchManSP";
chips.names[231] = "SearchManSP";
chips.names[232] = "SearchManDS";
chips.names[232] = "SearchManDS";
chips.names[233] = "MagnetMan";
chips.names[233] = "MagnetMan";
chips.names[234] = "MagnetManSP";
chips.names[234] = "MagnetManSP";
chips.names[235] = "MagnetManDS";
chips.names[235] = "MagnetManDS";
chips.names[236] = "Meddy";
chips.names[236] = "Meddy";
chips.names[237] = "MeddySP";
chips.names[237] = "MeddySP";
chips.names[238] = "MeddyDS";
chips.names[238] = "MeddyDS";
chips.names[239] = "ProtoMan";
chips.names[239] = "ProtoMan";
chips.names[240] = "ProtoManSP";
chips.names[240] = "ProtoManSP";
chips.names[241] = "ProtoManDS";
chips.names[241] = "ProtoManDS";
chips.names[242] = "NumberMan";
chips.names[242] = "NumberMan";
chips.names[243] = "NumberManSP";
chips.names[243] = "NumberManSP";
chips.names[244] = "NumberManDS";
chips.names[244] = "NumberManDS";
chips.names[245] = "Colonel";
chips.names[245] = "Colonel";
chips.names[246] = "ColonelSP";
chips.names[246] = "ColonelSP";
chips.names[247] = "ColonelDS";
chips.names[247] = "ColonelDS";
chips.names[248] = "ShadowMan";
chips.names[248] = "ShadowMan";
chips.names[249] = "ShadowManSP";
chips.names[249] = "ShadowManSP";
chips.names[250] = "ShadowManDS";
chips.names[250] = "ShadowManDS";
chips.names[251] = "TomahawkMan";
chips.names[251] = "TomahawkMan";
chips.names[252] = "TomahawkManSP";
chips.names[252] = "TomahawkManSP";
chips.names[253] = "TomahawkManDS";
chips.names[253] = "TomahawkManDS";
chips.names[254] = "KnightMan";
chips.names[254] = "KnightMan";
chips.names[255] = "KnightManSP";
chips.names[255] = "KnightManSP";
chips.names[256] = "KnightManDS";
chips.names[256] = "KnightManDS";
chips.names[257] = "ToadMan";
chips.names[257] = "ToadMan";
chips.names[258] = "ToadManSP";
chips.names[258] = "ToadManSP";
chips.names[259] = "ToadManDS";
chips.names[259] = "ToadManDS";
chips.names[260] = "ShadeMan";
chips.names[261] = "ShadeManSP";
chips.names[262] = "ShadeManDS";
chips.names[263] = "BlizMan";
chips.names[264] = "BlizManSP";
chips.names[265] = "BlizManDS";
chips.names[266] = "CloudMan";
chips.names[267] = "CloudManSP";
chips.names[268] = "CloudManDS";
chips.names[269] = "CosmoMan";
chips.names[270] = "CosmoManSP";
chips.names[271] = "CosmoManDS";
chips.names[272] = "LarkMan";
chips.names[273] = "LarkManSP";
chips.names[274] = "LarkManDS";
chips.names[275] = "GridMan";
chips.names[276] = "GridManSP";
chips.names[277] = "GridManDS";
chips.names[278] = "Django";
chips.names[279] = "DjangoSP";
chips.names[280] = "DjangoDS";

chips.names[301] = "Bass";
chips.names[302] = "DeltaRay";
chips.names[303] = "BugCurse";
chips.names[304] = "MetrKnuk";
chips.names[305] = "OMegaRkt";
chips.names[306] = "BassAnly";
chips.names[307] = "HolyDrem";
chips.names[308] = "BigHook";
chips.names[309] = "CrossDiv";
chips.names[310] = "BugCharg";
chips.names[313] = "Phoenix";
chips.names[314] = "DethPhnx";
--chips.names[###] = "LeaderR";
--chips.names[###] = "ChaosLrd";

function chips.get_random_code()
    return math.random(0,26);
end

local function get_valid(first_ID, last_ID)
    local ID = nil;
    while not chips.names[ID] do
        ID = math.random(first_ID,last_ID);
    end
    return ID;
end

function chips.get_random_ID_standard()
    return get_valid(  1, 180);
end

function chips.get_random_ID_mega()
    return get_valid(  1, 180);
end

function chips.get_random_ID_all_chips()
    return get_valid(  1, 180);
end

function chips.get_random_ID_PA()
    return get_valid(  1, 180);
end

function chips.get_random_ID_all()
    return get_valid(  1, 180);
end

return chips;

